version: '2'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /srv/dev-disk-by-label-Main8TBNAS/Config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
